### ISSUE TITLE
Error pada saat register pertama

### ISSUE THREAD

**Issue by irfan88** [nafiesl/silsilah#1]
Setelah proses install selesai, Coba register baru, terjadi error seprerti di bawah ini 

SQLSTATE[HY000]: General error: 1364 Field 'manager_id' doesn't have a default value (SQL: insert into `users` (`nickname`, `name`, `gender_id`, `email`, `password`, `updated_at`, `created_at`) values (Budi, budi hermawan, 1, budixxx@gmail.com, $2y$10$zkjU1Jx2MkQe9takWtDU1OMqWF.oijAb9jSYENg8zrQ1QoIatnJ/O, 2017-11-23 17:23:23, 2017-11-23 17:23:23))

manager_id fungsinya buat apa?

**Comment by nafiesl** [comment]
manager_id itu fungsinya sebagai pengelola mas. Jadi user yang menjadi manager id akan dapat meng-edit user yang bersangkutan. Terima kasih infonya mas. saya akan cek script registrasinya.

**Comment by nafiesl** [comment]
Sudah fixed mas @irfan88.
Coba : `git pull origin master`  ya mas.
Kemudian `php artisan migrate:refresh`. Baru coba register lagi.
