### ISSUE TITLE
[Proposal] Feature: Delete User

### ISSUE THREAD

**Issue by penjamoen** [nafiesl/silsilah#10]
apakah ada menu untuk  hapus data kalau misal terjadi kesalahan ?

**Comment by nafiesl** [comment]
Saat ini belum ada tombol untuk hapus User mas @penjamoen. Pertimbangannya, jika ada user yang sudah memiliki keturunan dihapus, maka jalur silsilah bisa putus. Masih belum ketemu formula yang pas untuk menghapus user tanpa memutus jalur silsilah.

Issue ini kita beri label sebagai improvement ya.

**Comment by penjamoen** [comment]
mungkin perlu di tambahkan di bagian tambah istri / tambah suami keterangan atau status nya . misal nya sudah cerai . karena disitu belum ada keterangannya jadi sepertinya wanita nya mempunyai 2 suami . terimakasih.

**Comment by nafiesl** [comment]
Kalau status cerai itu beda topik lagi mas, sebaiknya dibuatkan issue baru sebagai proposal fitur baru. Agar kita bisa keep track setiap usulan dari teman-teman pengguna project ini.

Terima kasih mas @penjamoen.

**Comment by ad3n** [comment]
@nafiesl : kalau misal sebelum hapus migrasi silsilah atau istilahnya reassign bisa ga ya? Jadi pas klik hapus kalau udah ada relasi maka muncul pop up untuk mengganti ybs dengan orang lain...

**Comment by nafiesl** [comment]
nah setuju mas @ad3n, berarti ada opsi untuk memilih user pengganti dulu ya? Jadi prosesnya ketika akan hapus user:
1. Muncul semacam popup atau modal ldialog pilihan user
2. User pengganti dipilih
3. Klik tombol "Replace and Delete User"
4. Sistem mengganti id user di semua record yang berhubungan
5. Data user dihapus dari aplikasi.

Mantap idenya mas Sur. Insyaallah saya coba terapkan untuk improvement ini.

**Comment by ad3n** [comment]
Iya mas kira-kira begitu... hehehe semangat mas, luar biasa projectnya

**Comment by nafiesl** [comment]
Terima kasih banyak mas Sur untuk idenya dan apresiasinya. Senang sekali dapat kontribusi ide dari mas Surya :+1:

**Comment by nafiesl** [comment]
Mas @penjamoen, mas @ad3n.
Fitur delete user dan pemilihan pengganti sudah selesai. :+1: 

Kalau mas ada waktu senggang, mungkin bisa `git pull` dan bantu review ya. :smiley: 
Terima kasih banyak mas-mas.

![shutter_20180601-005](https://user-images.githubusercontent.com/8721551/40845066-2996013e-65e8-11e8-9763-9c7665c8f1b4.jpg)
![shutter_20180601-006](https://user-images.githubusercontent.com/8721551/40845074-2c36e4da-65e8-11e8-9d25-ec10082ba3d8.jpg)

**Comment by ad3n** [comment]
Luar biasa... Mantab

**Comment by penjamoen** [comment]
siap mas .
