### ISSUE TITLE
Upload maksimal ukuran foto

### ISSUE THREAD

**Issue by saifalink** [nafiesl/silsilah#100]
mas @nafiesl untuk merubah ukuran max foto biar bisa lebih dari 200kb dimana ya

**Comment by nafiesl** [comment]
Di sini mas @saifalink 

https://github.com/nafiesl/silsilah/blob/260ff545047babee99e882777ab29837ef1a0081/app/Http/Controllers/UsersController.php#L210

Misal mau ukuran file maksimum 1 MB, maka `max:200` itu diubah jadi `max:1024`

**Comment by saifalink** [comment]
siap, makasih banyak mas.
