### ISSUE TITLE
Upload di cpanel tidak bisa update foto

### ISSUE THREAD

**Issue by saifalink** [nafiesl/silsilah#101]
mas @nafiesl  aku coba upload di cpanel software silsilah yang baru ini dan coba update foto tidak bisa tampil, mohon pencerahannya,
kalau pakai software yang lama bisa update foto.

**Comment by nafiesl** [comment]
mas @saifalink issue duplikat dengan https://github.com/nafiesl/silsilah/issues/93, silakan baca solusinya di sana ya.
