### ISSUE TITLE
Istri

### ISSUE THREAD

**Issue by 1HARI5AYAT** [nafiesl/silsilah#108]
Apa bisa nama istri dampilkan dipohon keluarga ?

**Comment by nafiesl** [comment]
Halo pak @1HARI5AYAT, hal ini sudah ada pembahasan di sini  https://github.com/nafiesl/silsilah/issues/84#issuecomment-1095175774

Issue ini saya close.

**Comment by 1HARI5AYAT** [comment]
Baik mau saya simak bang

**Comment by 1HARI5AYAT** [comment]
Maksd saya itu pencantuman nama istri supaya keluarga tahu namanya. Dan
bisa di cetak itu bang

Pada tanggal Min, 6 Agu 2023 17.19, Nafies Luthfi ***@***.***>
menulis:
