### ISSUE TITLE
Nama

### ISSUE THREAD

**Issue by 1HARI5AYAT** [nafiesl/silsilah#110]
Untuk menampilkan nama istri/suami saja dipohon keluarga apa bisa bang. Supaya sodara-sodara tahu nama istri/suaminya. Pas bisa dicetak jadi buku

**Comment by nafiesl** [comment]
Yang menampilkan nama pasangan di pohon keluarga, sudah dibahas di sini mas: https://github.com/nafiesl/silsilah/issues/84#issuecomment-1095175774

Kalau mas berkenan kontrubusi untuk bikin fiturnya, akan sangat bagus mas.
