### ISSUE TITLE
I have many questions about your project

### ISSUE THREAD

**Issue by gusbemacbe** [nafiesl/silsilah#112]
Good morning!

1. Does your project support the mesh structure? For example, I want to add the families of both maternal and paternal, and to add uncles or aunts' spouses, their children, and grandchildren, etc., and the cousins' spouses, their children, and grandchildren, etc., and to add 4 grandparents with their siblings and in laws, and 8 great-grandparents with their siblings and in laws, etc. Until the 16th generation. 
2. Can I add new person attributes, for example, citizenship and ancestries?
3. Can I customise the cards style?
4. Can I unfold and keep expanding the entire genealogy?
5. Can I export the entire unfolded genealogy to PNG, PDF and SVG?

Thank you for your attention!

**Comment by nafiesl** [comment]
I am closing this issue since no response. Thanks
