### ISSUE TITLE
Instalasi gagal karena tidak ada folder Vendor

### ISSUE THREAD

**Issue by haamadh** [nafiesl/silsilah#120]
Halo Mas.

Saya mencoba melakukan instalasi dan saya stuck saat harus melakukan 'composer install' karena folder vendor tidak tersedia.

Apakah ada saran?

![image](https://github.com/user-attachments/assets/9cb49011-75c7-40e9-915b-de32912a6770)

terima kasih

**Comment by nafiesl** [comment]
halo mas @haamadh folder vendor memang tidak ada saat kita clone source codenya mas. Folder vendor di-generete saat kita menjalankan `composer install`.

Adapun problem yang mas alami, kemungkinan besar dikarenakan masalah permission saja (tidak dapat create folder vendor). Coba googling dengan kata kunci ini mas: 
```
how to run composer install properly in /var/www directory (which need sudo)?
```
Atau bisa juga tanya chat gpt.

**Comment by haamadh** [comment]
Baik. Terima kasih banyak informasinya. Sepertinya saya ada permasalahan di access permission. Terima kasih
