### ISSUE TITLE
[PROPOSAL] Add Change Password Feature

### ISSUE THREAD

**Issue by nafiesl** [nafiesl/silsilah#14]
Currently our user don't have a feature to change password. We need a change password page for logged in user.

Change password flow :
- User must be logged in
- User click the "Change Password" menu/link
- User must fill in the old password, new password and confirm new password.
- System checks that old password is correct
- If old password correct, save new password
- Else, notify user that old password is incorrect.

Thanks.

**Comment by tthompson899** [comment]
I’d like to take a stab at this one

**Comment by nafiesl** [comment]
Sure @tthompson899

**Comment by cendekia** [comment]
@nafiesl Sudah kelar ya Mas 😉

[https://github.com/nafiesl/silsilah/pull/15#issue-223716457](PR#15)

**Comment by tthompson899** [comment]
@cendekia Thanks for the update.

**Comment by nafiesl** [comment]
@cendekia thanks for the your PR, but i think change password feature on the profile edit page will be used by user manager to change their managed user's password.
Actually i thought something like this will be better.

![selection_18101807 41 18](https://user-images.githubusercontent.com/8721551/47122418-38db4400-d2a9-11e8-8736-23f52cb019b2.png)

You might want to take a look at this source code example, if it can help : [ChangePasswordController](https://github.com/nafiesl/dompet/blob/master/app/Http/Controllers/Auth/ChangePasswordController.php).

Thanks.
