### ISSUE TITLE
Request to add Haji & Hajah

### ISSUE THREAD

**Issue by imie** [nafiesl/silsilah#18]
can you please add option like tick box to auto add title of haji/hajah to the person ?

**Comment by nafiesl** [comment]
Hmm.. I do not think this is necessary. I understand what you meant, but i think i cannot accept this proposal. Besides, you can add H. or Hj. inside person name, or rather, you can add this feature on your forked repository.

**Comment by biplobice** [comment]
I agree with @nafiesl
