### ISSUE TITLE
Request to add order to poligamy wife

### ISSUE THREAD

**Issue by imie** [nafiesl/silsilah#19]
Can you please add the order if have multiple wives ?

my great2 grandfather was having 5 wives. and how to show which child belongs to which mother.

below is sample of my family tree. my great grandma is from the 2nd wife.

![2](https://user-images.githubusercontent.com/2321338/48930548-37e2a580-ef2c-11e8-9b5b-2f093cf14263.JPG)

![1](https://user-images.githubusercontent.com/2321338/48930550-37e2a580-ef2c-11e8-8378-46779e2d3a61.JPG)

**Comment by nafiesl** [comment]
Good idea, we will see what we can do to implement your proposal.

**Comment by nafiesl** [comment]
Hi @imie, your proposal has been implemented on this commit b1380e9.

The order of multiple wife/husband records will be **sorted by their marriage date**. So, if you want to sort person couple names based on marriages order, you can provide their `marriage_date` (even if you using fake date).

Please give it a try.

We will close this issue. You can re-open this issue if you found any problem with this feature. Thanks for your contribution.
