### ISSUE TITLE
GEDCOM

### ISSUE THREAD

**Issue by curtisdelicata** [nafiesl/silsilah#2]
Do you have any plans to support importing or exporting of GEDCOM files?

**Comment by nafiesl** [comment]
I didn't know about GEDCOM before. I'm just knew about it from you. Do you have a plan to build an opensource genealogy software too? With GEDCOM standardized data structure?

**Comment by curtisdelicata** [comment]
Yes I am planning an open source genealogy software. I have not made final decision on whether to contribute to an existing project as there are so many options using different programming languages. 

However if I design from scratch most likely will be Laravel.

**Comment by nafiesl** [comment]
You may be continue working on forked repo on this project. This project contains feature and unit testing that might help you to continue on.
We may discuss for some more feature for this project, or your own project if you want.

Right now, i can't really spent much time to build new feature on this project.
