### ISSUE TITLE
[tanya] family chart 

### ISSUE THREAD

**Issue by alfarioekaputra** [nafiesl/silsilah#20]
selamat sore, pada family chart ini kenapa tidak ada nama suaminya ya? pada nama masitah baderi

![image](https://user-images.githubusercontent.com/650641/49727383-b9fbf980-fca2-11e8-9e0e-861068a6eae3.png)

**Comment by nafiesl** [comment]
Sore mas @alfarioekaputra, untuk family chart dan family tree memang tidak menampilkan pasangan mas. Karena di family chart dan family tree, hanya fokus pada garis keturunan saja, jadi tidak menampilkan pasangan, baik untuk person yang dilihat, maupun keturunan dibawahnya.
