### ISSUE TITLE
how to publish it to public hosting

### ISSUE THREAD

**Issue by 1anshari** [nafiesl/silsilah#23]
hi akhi,
when i think it's need to publish, my brother and sister self entry to this database; but i don't understand how to publish it to my domain/hosting public
i use host : tryfcomet.com

how to type on cpanel : 
php artisan key:generate
and type : 
php artisan migrate
php artisan storage:link
php artisan serve

i already create database, copy extract to filemanager, and edit .env, but it's can't work.
is any example site demo's can work to apply it?

it's great idea, i can't wait it... thank you verymuch

my number : wa.me/628561515628
wassalaamu'alaikum

**Comment by nafiesl** [comment]
Hi akhi @1anshari,
Sorry for my late respons. Did you success install this software in localhost? Xampp or any other local environment?

**Comment by 1anshari** [comment]
yes i use xampp windows, and it running well.
i think because i typing-script on powershell or cmd "php artisan migrate" for creating database.
but i can't found how to type these script on cpanel.

i'm so sorry i'm difficult on english and so bad.

**Comment by biplobice** [comment]
@1anshari 
It depends on your cPanel. You can ask your cPanel provider, does it support the laravel application. Or, you can set it up by yourself.

Simply what you can do, export & import the database through `phpMyAdmin` and upload the files through FTP. I believe it'll work.

**Comment by nafiesl** [comment]
Aggree with @biplobice.

If the project runs well on xampp windows, and your hosting provider has at least php 7.1.3, you can do following steps :
1. zip your silsilah project folder in localhost (eg. silsilah.zip).
2. export your localhost database with phpmyadmin as sql or zip file (eg. silsilahdb.sql.zip).
3. upload the silsilah.zip file to public_html or other folder with ftp or cpanel file manager.
4. extract silsilah.zip to a folder (eg. /silsilah or other folder).
5. edit .env file to match your database name, db username and db password.
6. import the silsilahdb.sql.zip to your created database.
7. (optional) create a subdomain and document root to public folder (eg. /silsilah/public).

I think it should work.

> PS:
> 1. avoid to extract and use folder outside public_html, for security reason.
> 2. I can speak Indonesian, because i am from Banjarmasin, South Kalimantan :smile:

**Comment by ariyako** [comment]
Salam dari malaysia! bagus cadangan  @1anshari . jika boleh memudahkan lagi proses setup ke hosting.

bagaimana boleh saya menyumbang "translation" ke Bahasa Melayu ?

**Comment by nafiesl** [comment]
Salam pak @ariyako. Sure pak, sila buat PR untuk Melayu translation ya. :+1:

**Comment by 1anshari** [comment]
abang, saya mau tanya,
![image](https://user-images.githubusercontent.com/30915472/55045136-66ee5c80-506f-11e9-87fc-33a6795dcdda.png)
orang tua itu diisinya dengan apa ya? betulkah diisi dengan nama ayah dan nama ibu?

**Comment by nafiesl** [comment]
Sudah betul mas @1anshari orang tua itu diisi dengan pasangan pernikahan orang tua.

**Comment by 1anshari** [comment]
tinggal konfigurasi di hosting nya yang belum; 
saya pakai hosting gratisan di tryfcomet.com
kalau mohon bantuan abang boleh?
bagaimana saya menyampaikan password cpanel saya ke abang tetapi tidak di publik github ini, boleh minta nomor wa abang? atau ada cara lain?

**Comment by nafiesl** [comment]
mas @1anshari mohon maaf untuk setup di hosting saya belum bisa bantu. Secara umum, prosesnya seperti yang saya jelaskan diatas https://github.com/nafiesl/silsilah/issues/23#issuecomment-474187811.

Silakan coba search cari di google cara upload aplikasi laravel di shared hosting saja. :pray:
