### ISSUE TITLE
Wrapping not running

### ISSUE THREAD

**Issue by imanueli2312** [nafiesl/silsilah#29]
Dear Bung Nafiesl,

Kok wrapping ngga jalan kalau dibuka dengan menggunakan browser chrome  tpi jika menggunakan IE aman sentosa ?

dibawah dengan menggunakan IE
![image](https://user-images.githubusercontent.com/42263478/64329248-24a35100-cff9-11e9-997d-7ed2fb93f506.png)

Dibawah dengan menggunakan Chrome
![image](https://user-images.githubusercontent.com/42263478/64329201-0d646380-cff9-11e9-9ead-48ec6a7c1ad0.png)

Terima kasih.

**Comment by nafiesl** [comment]
Halo mas @imanueli2312, saya sudah test di Chromium dan Firefox, tetapi saya **tidak bisa reproduce** bug yang sama.
 
Apakah mas sudah refresh halaman dan tetap mengalami bug yang sama? Asumsi saya, hal itu terjadi karena jquery plugin **select2** tidak bersifat responsive (kecuali kita refresh halaman web). 

**Chromium**

![Selection_tp_190908016](https://user-images.githubusercontent.com/8721551/64489816-fdaf7e00-d289-11e9-89b4-bc2a73bfceb7.jpg)

**Firefox**

![Selection_tp_190908019](https://user-images.githubusercontent.com/8721551/64489851-4830fa80-d28a-11e9-8844-328c64715c32.jpg)
