### ISSUE TITLE
Password Lama

### ISSUE THREAD

**Issue by novis97** [nafiesl/silsilah#36]
Pada page profile, pada Akun Login ada 2 isian : email dan password lama.  Passowrd lama maksudnya apa ya? Mungkin yg dimaksud adala "Ppassword" saja.

**Comment by nafiesl** [comment]
halo mas @novis97, saya baru saja menemukan issue yang mas informasikan ini. Ternyata yang mas maksud adalah pada halaman **Edit Profil** user ya.

![screen_20-03-15_008](https://user-images.githubusercontent.com/8721551/76701686-3f6c2600-66fe-11ea-8162-47ed61d4d375.jpg)

Di sini tertulis `Password Lama` atau `Old Password`.

Ok ini akan kita perbaiki mas. Terima kasih report issuenya mas @novis97 :pray:
