### ISSUE TITLE
Error setelah menghapus pasangan?

### ISSUE THREAD

**Issue by novis97** [nafiesl/silsilah#37]
Web jadi error setelah menghapus pasangan. Adakah solusi?
PHP 7.2
Laravel 5.8
Mysql

![WhatsApp Image 2019-11-21 at 21 03 20](https://user-images.githubusercontent.com/8391319/69347863-d290d400-0ca7-11ea-8caa-5f72cde6afb1.jpeg)

**Comment by nafiesl** [comment]
Setelah diskusi dengan mas @novis97, ternyata ketika hapus user, tidak diantisipasi bahwa record pasangan masih tertinggal. Misal contoh kasus:
- Sepasang suami isteri
- User suami dihapus
- Record pasangan suami isteri masih ada (dengan ID suami masih tampil)

### Alternatif solusi

**Solusi 1**
Tampilkan nama berupa "N/A"
Misal : Suami Agus, Isteri Fitri.
User Agus dihapus, maka ketika menampilkan nama suami dari record pasangan, tampilkan "N/A".

**Solusi 2**
Hapus record pasangan.
Ketika user dihapus, record pasangannya juga dihapus dari sistem

**Solusi 3**
Cegah hapus user.
Ketika user akan dihapus, karena ada record pasangan, maka user tidak dapat dihapus.
