### ISSUE TITLE
Input Tanggal Pernikahan

### ISSUE THREAD

**Issue by EdyJo** [nafiesl/silsilah#4]
Perlu ditambah **link atau tombol untuk menginput tanggal pernikahan**. Bisa ditambahkan hanya dengan langsung mengedit database.

**Comment by nafiesl** [comment]
Noted mas, ini bisa kita akomodir nanti jika kita buatkan halaman edit pernikahannya.

**Comment by nafiesl** [comment]
Done mas @EdyJo, sudah ditambahkan tanggal pernikahan pada saat tambah pasangan, dan pada edit pernikahan.

### Tambah Pasangan (Suami/Isteri)

![shutter_20180228-001](https://user-images.githubusercontent.com/8721551/36762213-8257f018-1c5d-11e8-9094-1276ef25b695.jpg)

### Edit Pernikahan

![shutter_20180228-002](https://user-images.githubusercontent.com/8721551/36762222-8c037fb0-1c5d-11e8-8918-674a8002479b.jpg)
