### ISSUE TITLE
profile photo unable to dispaly in profile.blade.php

### ISSUE THREAD

**Issue by sarojbrt1** [nafiesl/silsilah#40]
profile photo not working while updatin..

**Comment by sarojbrt1** [comment]
> profile photo not working while updating..

**Comment by nafiesl** [comment]
Hello @sarojbrt1. Have you been run `php artisan storage:link` on the project?

**Comment by sarojbrt1** [comment]
@nafiesl  image upload work fine.. but i am unable to display in profile,,

**Comment by nafiesl** [comment]
I cannot reproduce the issue. On my locahost which uses Linux Mint 18.3, PHP 7.2.

Here are my local screenshots after uploading the image profile.

![screen_20-02-02_002](https://user-images.githubusercontent.com/8721551/73606910-93a5c580-45ea-11ea-8ea8-7e7cc827e753.jpg)

![screen_20-02-02_001](https://user-images.githubusercontent.com/8721551/73606913-96a0b600-45ea-11ea-9d58-890f13d02ff4.jpg)

![screen_20-02-02_003](https://user-images.githubusercontent.com/8721551/73606908-8d174e00-45ea-11ea-8590-9613ab00a147.jpg)

You might haven'r run the `php artisan storage:link` command, as noted on [**Installation Steps** point 9](https://github.com/nafiesl/silsilah#installation-steps), @sarojbrt1.
