### ISSUE TITLE
profile image work fine in local host  but it doesnt work in live server>

### ISSUE THREAD

**Issue by sarojbrt1** [nafiesl/silsilah#42]

**Comment by sarojbrt1** [comment]
@nafiesl  any solution?

**Comment by nafiesl** [comment]
Sorry @sarojbrt1, you didn't specify any server specification, I have no clue regarding your issue. From me, as long as you have met these requirements and installation steps, you should be fine on the server or localhost.

https://github.com/nafiesl/silsilah#how-to-install

Unless you missed some installation steps.

**Comment by sarojbrt1** [comment]
@nafiesl  we are using cloud hosting direct admin panel...

**Comment by nafiesl** [comment]
Have you run this command on your server @sarojbrt1?
```
php artisan storage:link
```

**Comment by nafiesl** [comment]
Hi @sarojbrt1, I consider this issue has been resolved, since no more feedback from you. I am closing this Issue since. Feel free to reopen it if you need so. Thanks.
