### ISSUE TITLE
Error exception upon attempting to register a new user. 

### ISSUE THREAD

**Issue by akhan85** [nafiesl/silsilah#43]
When trying to register a new user, I receive an Error Exception as such:
'Trying to access array offset on value of type null'

The issue appears to originate from line 147 in the /vendor/egulias/email-validator/EmailValidato/Parser/Parser.php file

<img width="847" alt="image" src="https://user-images.githubusercontent.com/8957062/74670074-69b9da80-5176-11ea-8f7e-805abed75244.png">

Any help in this regard would be greatly appreciated. Thank you for your contribution!

**Comment by nafiesl** [comment]
Hi @akhan85, thanks a lot for the report. I will look into it. Sorry for my late response.

**Comment by akhan85** [comment]
Hi @nafiesl, thank you for looking into it. And no need to apologize. I appreciate the fact that you're sharing your knowledge and taking the time to address issues.

**Comment by nafiesl** [comment]
@akhan85, I found that this issue happens only on php 7.4, but not occurs on php 7.2 (in my localhost). I see the same issue here https://github.com/laravel/framework/issues/30737#issuecomment-579277858.

**Comment by akhan85** [comment]
@nafiesl, worked like a charm! Thank you for the speedy turnaround.

**Comment by nafiesl** [comment]
Great @akhan85, I am closing this issue. Thanks.

**Comment by akhan85** [comment]
Thank you so much! I just have one more question and I don't want to open
up an issue for it but I was wonder if there was a way to recover a
password from the database for an account created without using the forgot
password feature. Currently I run into an error if i attempt to do that
probably because I am running a local DB instance on my laptop and haven't
hosted the application anywhere.

Thank you!

**Comment by nafiesl** [comment]
Hi @akhan85, I am not clear enough about your new issue. I think you can create a new issue if you found a different error. 

It would be best if you can describe steps to reproduce it and attach some screenshot just like you did in this issue. Then we can investigate it together.
