### ISSUE TITLE
Delete wife/husband query

### ISSUE THREAD

**Issue by masbz0ne** [nafiesl/silsilah#48]
Hi,

I would like to request the user can delete the wife/husband if example the user entered the name twice. So if the user want to delete the wife/husband and merge together it will cause an error as attached.

![image](https://user-images.githubusercontent.com/63302455/78681071-d9e71000-791e-11ea-9a88-bdd629353b39.png)

I will assume that the couple_husband is attached with the same key.

Thank you

**Comment by nafiesl** [comment]
Thanks for report @masbz0ne, I will take a look at this issue.
