### ISSUE TITLE
Update Urutan Berdasarkan Tanggal Lahir

### ISSUE THREAD

**Issue by EdyJo** [nafiesl/silsilah#5]
Urutan anak dalam keluarga berdasarkan urutan penambahan user. Sebaiknya, setelah user menambahkan tanggal lahir, urutan anak diupdate secara otomatis **berdasarkan tanggal lahir**.

**Comment by nafiesl** [comment]
Untuk urutan anak, rencana akan dibuatkan peng-urutan dengan drag-and-drop mas, jadi nanti setiap user punya kolom semacam "urutan anak" untuk menandakan si user tadi anak ke berapa dari keluarganya.

Kalau kita urutkan otomatis dari tanggal lahir sebenarnya bisa, tapi dengan kondisi saat ini, agak kesulitan mengumpulkan data user lengkap dengan tanggal lahirnya.

**Comment by ardantus** [comment]
Cara Mengurutkannya bagaimana ya, apakah tidak sebaiknya diurutkan manual saja karena umumnya data itu minimalis jadi lebih prefer ke diurutkan manual dan di beri angka sesuai urutan lahirnya. sehingga bisa diketahui anak pertama kedua dan seterusnya.

**Comment by nafiesl** [comment]
Betul mas @ardantus, rencana akan dibuatkan urutan manual, jadi nanti fiturnya seperti drag and drop. Urutan ini akan dibuat melalui halaman detail pasangan (couple) orang tuanya.

Tapi mungkin nanti kita bisa tambahkan juga field edit nomor urut kelahiran di halaman edit user.
