### ISSUE TITLE
Error when try to do backup from Database Backup Manager

### ISSUE THREAD

**Issue by imie** [nafiesl/silsilah#51]
Running the program through windows and encounter error on the backup module.

Ada missing some configuration ka ?

![23](https://user-images.githubusercontent.com/2321338/79233672-c2b69e00-7e9b-11ea-8a5a-bd61a3f60734.PNG)

**Comment by nafiesl** [comment]
Hi @imie, lLooks like mysql folder in the wamp server has not been added to windows environment path variable. After you set it, you can try to run "mysql" command on the cmd, if you do can run it, then this error should be resolved.

**Comment by nafiesl** [comment]
Closing this issue since it does not active. Feel free to re-open this if you have further discussion regarding this issue.
