### ISSUE TITLE
Update di Edit profile password hilang

### ISSUE THREAD

**Issue by getheboxs** [nafiesl/silsilah#59]
terima kasih telah membuat aplikasi yang bagus sekali, setelah dicoba saya menemukan hal seperti ini

di bagian **Edit Profile**, ketika di tekan tombol **Update** dengan kondisi kolom **Password** kosong, menyebabkan password dari user tersebut hilang/kosong, 
mungkin bisa di berikan pengecekan, ketika kosong maka password tetap, tetapi kalau di isi maka password di ganti,

terima kasih

**Comment by issh1989** [comment]
Before two minutes I added the pull request to remove the password from request if null
You can see I and change your code like it.
#60
