### ISSUE TITLE
Redirect domain to domain/public

### ISSUE THREAD

**Issue by imie** [nafiesl/silsilah#6]
lepas install dekat web hosting, gimana mau automatic redirect to public folder when enter domain.

e.g. qysteena.net straight away open the qysteena.net/public

sekarang ni terpaksa gune subdomain untuk redirect.

e.g. salasilah.qysteena.net

**Comment by nafiesl** [comment]
Hai, silakan coba tutorial ini untuk install Laravel project pada Cpanel:
http://www.rumahweb.com/journal/cara-upload-laravel-ke-hosting-cpanel.htm
