### ISSUE TITLE
Pin lokasi makam

### ISSUE THREAD

**Issue by novis97** [nafiesl/silsilah#63]
Maaf, mau usul aja. Saya lihat ada fitur tanggal meninggal, gimana kalau ditambahkan lokasi pemakaman dalam bentuk pin map google,. Sptnya cocok diterapkan di laravel ini. karena kalau bicara silsilah maka tak lepas dari leluhur. Apalagi dengan tradisi takziah (mengunjungi maka) bagi banyak orang di Indonesia.

Terima kasih

**Comment by nafiesl** [comment]
Siap mas @novis97, kita note dulu untuk improvement.

Untuk pin lokasi dan petanya, kita bisa ambil referensi dari project ini.
https://github.com/nafiesl/laravel-leaflet-example

**Comment by nafiesl** [comment]
Halo mas @novis97, di Pull Request ini #68 saya mengembangkan fitur agar user dapat memberikan pin lokasi peta untuk orang/anggota keluarga yang sudah meninggal dunia. Saat ini masih proses development.

**Comment by novis97** [comment]
Alhamdulillah. Semoga lancar

**Comment by nafiesl** [comment]
Halo mas @novis97 maaf baru selesai fiturnya, sekarang bisa dicoba git pull master terbaru mas, kemudian jalankan php artisan migrate untuk untuk dapat fiturnya.

Karena sudah selesai, issue ini saya tutup. Silakan issuenya dibuka lagi jika diperlukan.

Terima kasih masukannya mas.
