### ISSUE TITLE
Error saat install project Silsilah di PHP 8.x

### ISSUE THREAD

**Issue by pemburu-kage** [nafiesl/silsilah#69]
Saat proses composer install, saya ketemu error ini:
```
Your requirements could not be resolved to an installable set of packages.
```
Screenshot:
![error](https://user-images.githubusercontent.com/17373530/119591354-07379b80-be09-11eb-9136-4675773db623.jpg)

**Comment by nafiesl** [comment]
Halo mas @pemburu-kage, kalau dari errornya, ini ada 2 issue:
1. Versi PHP ketinggian, seharusnya maksimal php 7.4.
2. Extension php fileinfo tidak aktif.

Ini yang bisa dilakukan
1. Untuk issue nomor 1, bisa downgrade versi PHP localhostnya ke 7.3 atau 7.4. Tetapi saya berencana untuk menambah support ke php 8.x. Akan saya update lagi kalau sudah support php 8.x
2. Untuk issue nomor 2, bisa coba aktifkan php extension fileinfo (jika sudah aktif, cek php info akan dapat seperti gambar di bawah)

![screen_2021-05-26_005](https://user-images.githubusercontent.com/8721551/119600916-a3b66980-be1a-11eb-9b4a-c76cfe2912b7.jpg)

Terima kasih.

**Comment by nafiesl** [comment]
Halo mas @pemburu-kage, PR #71 berisi support php 8.0 sudah merge ke master, kalau mau coba bisa pull branch `master` terbaru. Mestinya sudah sip di php 8.0. Terima kasih.
