### ISSUE TITLE
Error , Setelah Logout tidak bisa Login Kembali

### ISSUE THREAD

**Issue by vickyKDV** [nafiesl/silsilah#7]
1. Pesan error setelah logout "Identitas tersebut tidak cocok dengan data kami.", padahal tidak lupa password dan user name, bagaimana mengatasinya ?, 
2. Project saya taurh web site dan masalahannya tidak bisa upload gambar, hanya bisa di localhost saja, apakah ada solusi , mas ?

**Comment by nafiesl** [comment]
mas @vickyKDV, untuk yang nomor 1, saya cek lagi mas.

Untuk yang nomor 2, gambar akan terupload ke direktori storege/public/images mas. Jadi kita harus menggunakan symlink agar bisa terbaca gambarnya (php artisan storage:link).

Kalau ditaruh di website, apakah menggunakan shared hosting? atau VPS?
Kalau shared hosting apakah support symlink? kalau tidak support symlink, berarti codingnya mesti diubah agar uploadnya ke folder public mas.

**Comment by nafiesl** [comment]
Coba mas @vickyKDV trial disini mas: http://silsilah.nafies.id
Coba register, logout, dan login lagi. Coba upload foto juga mas.

Ini barusan saya deploy dengan commit terbaru.

**Comment by vickyKDV** [comment]
Untuk upload foto seperti sudah bekerja secara baik mas, 
Untuk website saya pakai shared hosting mas @nafiesl apakah saat ini sudah support scriptnya untuk shared hostingnya mas @nafiesl ?,
Untuk login saya perlu waktu beberapa saat untuk logout dan login lagi.

**Comment by vickyKDV** [comment]
Untuk login ternyata masih bermasalah mas @nafiesl, masih error seperti sebelumnya ,mohon update nya mas.

**Comment by nafiesl** [comment]
mas @vickyKDV, kalau untuk masalah login, coba trial disini aplikasi demo ini mas: http://silsilah.nafies.id, kalau yang di aplikasi demo brmasalah loginnya, silakan di info mas.

tetapi kalau yang bermasalah login di shared hosting atau di localhost mas Viicky, saya belum bisa bantu, karena di localhost saya dan di server demo ga ada masalah. :grin:

**Comment by nafiesl** [comment]
Untuk support ke shared hosting, saya kurang tahu mas, karena saya belum coba deploy ke shared hosting.

**Comment by vickyKDV** [comment]
Sebelumnya dilocalhost masalah login ya sama kayaknya mas, cuma untuk update nya saya belum coba, 😅
Untuk shared hosting coba saya cari solusi nanti mas, moga bisa diselesaikan 😊, 
Kalo fungsi token_id itu sendiri untuk apa mas di kolom user.

**Comment by vickyKDV** [comment]
Untuk yang trial saya coba saat ini ga bisa login mas, padahal pas coba awal sudah register dan terdaftar tapi setelah coba kembali "identitas tidak ditemukan" pesan galatnya

**Comment by vickyKDV** [comment]
Ternyata permasalahannya adalah kita mesti pakai password bertipe number, jadi kalo pakai huruf dia tidak bisa mas, karna setelah pakai number saya selalu berhasil login, tidak seperti sebelumnya, dan yang sebelumnya tidak bisa login saya ganti password menggunakan number, ternyata langsung bisa...

**Comment by vickyKDV** [comment]
done,, load & save foto via shared hosting...


function.php
---------------------------------
function userPhotoPath($photoPath, $genderId)
{
    if (is_file(public_path('profile/'.$photoPath))) {
        return asset('profile/'.$photoPath);
    }
---------------------------------
agar bisa load di shared hosting.

dan sedikit perubahan untuk di simpan foto nya

filesystem.php
-------------------------------
    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => public_path('profile'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => public_path('profile'),
            'url' => env('APP_URL').'profile',
            'visibility' => 'public',
        ],
------------------------------

**Comment by vickyKDV** [comment]
Mas, bisa ditambahkan untuk menu hapus data tidak ya, ketika edit data, buat antisipasi karna kadang ada 2 nama yang sama terbuat

**Comment by nafiesl** [comment]
Saya belum ada planning untuk menambahkan fitur itu. Kalau mas @vickyKDV mau kontribusi di project ini untuk fitur itu, saya persilakan mas.

**Comment by vickyKDV** [comment]
Oke mas @nafiesl ,siap untuk kontribusi buat fitur hapusnya 😊👌
