### ISSUE TITLE
Error saat ingin mereset password pada halaman lupa password

### ISSUE THREAD

**Issue by pemburu-kage** [nafiesl/silsilah#70]
![error lagi](https://user-images.githubusercontent.com/17373530/119661008-6e356e80-be62-11eb-9508-727bb2a150c3.jpg)

**Comment by nafiesl** [comment]
Halo mas @pemburu-kage, bisa dibuatkan cara reproduce bugnya (tahapan proses sampai dapat bugnya)?

Berikut contoh laporan bug yang baik: https://github.com/nafiesl/SimpleCrudGenerator/issues/39, supaya lebih mudah dam menghemat waktu untuk mencari solusinya.

Terima kasih.

**Comment by pemburu-kage** [comment]
symasuk ke halaman lupa password kemudian setelah memasukkan email ke form lalu mereset passwod terjadi error :
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required "

**Comment by nafiesl** [comment]
Issue ini kita close karena 3 opsi solusi di atas seharusnya sudah cukup menjawab. Terima kasih.
