### ISSUE TITLE
Set default language

### ISSUE THREAD

**Issue by nolbyte** [nafiesl/silsilah#72]
Hi!
Can we set default language to id when people open the page for the first time?
Thank you

**Comment by nafiesl** [comment]
Hello @nolbyte, to change your default language, you can update this code:
https://github.com/nafiesl/silsilah/blob/master/app/Http/Middleware/Lang.php#L18

To:
```
app()->setLocale(request('lang', session('lang', 'id')));
```

The default lang will be `id`.

**Comment by nolbyte** [comment]
Ok, done.
