### ISSUE TITLE
Error Saat Edit Profile

### ISSUE THREAD

**Issue by nolbyte** [nafiesl/silsilah#73]
Halo,
Saya baru saja melakukan update dengan perintah **git pull** karena saya lihat ada perubahan di repo utama. Tapi mendapat error ketika melakukan edit profile seperti berikut
![bani-mahrup](https://user-images.githubusercontent.com/6904781/122634282-730adc80-d107-11eb-9319-105e9b1e4226.png)
Dikatakan bahwa table user_metadata tidak ditemukan.
Apakah bisa dilakukan perbaikan dengan perintah migrate?
Terima kasih

**Comment by nafiesl** [comment]
Halo mas @nolbyte. Sip sekarang tinggal jalankan artisan migratenya mas:
```
php artisan migrate
```

**Comment by nolbyte** [comment]
Alhamdulillah
Work like a charm
Hatur nuhun
