### ISSUE TITLE
How to deploy in cpanel?

### ISSUE THREAD

**Issue by samkoba** [nafiesl/silsilah#82]
is there a tutorial how? I have a problem when deploying in cpanel

Please help. thank you

<img width="990" alt="image" src="https://user-images.githubusercontent.com/7510963/157033760-b83cd53e-efa8-4959-a18d-1fb6c1e2663c.png">

<img width="849" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/7510963/157033484-6eb71491-5785-4f70-9253-3152f36d37a3.png">

**Comment by nafiesl** [comment]
Hi @samkoba, I can see the issue is caused by the PHP version. You were using PHP 8.0, but this project requires PHP 7.3 - 7.4.

The current possible solution: you downgrade PHP version from 8.0 to 7.4. Then try to run the composer install again using PHP 7.4.

Let us know if the solution works for you.

Thanks.

**Comment by samkoba** [comment]
oh my god, this works. Thank you very much.

But do you know how to remove the debug feature listed below? very annoying for production

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/7510963/157054295-6a73c672-fd2a-443c-87f2-ccd96464989f.png">

**Comment by samkoba** [comment]
it really works. thank you very much.

Sorry, this is my last question.

In the silsilah only shown until the "wereng" (5th generation). I want to show up to the 10th generation. Where can I change it?

**Comment by nafiesl** [comment]
No problem, @samkoba.

Correct, we just show 5 generations there. You can continue showing the next generations by editing this file:

https://github.com/nafiesl/silsilah/blob/master/resources/views/users/tree.blade.php

You can check on these parts to see how it is structured:
```
...
<div class="branch lv4">
<div class="branch lv5">
```

**Comment by samkoba** [comment]
very helpful. thank you for answering my questions
