### ISSUE TITLE
Tambah Foto

### ISSUE THREAD

**Issue by RomziJazz** [nafiesl/silsilah#86]
Tambah Foto pada setiap orang, biar pengenalnya lebih detail.

**Comment by nafiesl** [comment]
Halo mas @RomziJazz, di silsilah terbaru di branch master sudah ada fitur foto profilnya untuk tiap person mas.

![20220503_205010](https://user-images.githubusercontent.com/8721551/166456060-ea814ab9-4ad4-41c5-93d1-0d0dabb966bb.jpg)

Issuenya saya close ya, silakan open lagi jika diperlukan.
