### ISSUE TITLE
Menampilkan pasangan di family tree

### ISSUE THREAD

**Issue by ulimahendra** [nafiesl/silsilah#87]
Ijin Mas... sya berterimakasih sekali ada aplikasi yg mas buat ya.. ijin saya gunakan untuk trah saya..
Yang mau sya tanyakan mas.. apa bisa menampilkan pasangan di pohon keluarganya ya..
supaya pasangan juga terlihat langsung di pohon keluarga..
Terimakasih

**Comment by nafiesl** [comment]
Halo mas @ulimahendra fyi: https://github.com/nafiesl/silsilah/issues/84#issuecomment-1095175774

**Comment by ulimahendra** [comment]
Aamiin mas.. jadi belum bisa ya mas klo untuk nampilin kayak gini mas...
![image](https://user-images.githubusercontent.com/75785497/183242506-75556a16-d314-4a83-a610-0c70d49aa9f1.png)

**Comment by nafiesl** [comment]
@ulimahendra belum bisa mas, tampilan seperti itu cocok kalau 1 orang hanya 1 pasangan (isteri atau suami). Sedangkan di sistem silsilah ini, 1 orang bisa lebih dari 1 isteri/suami (misal cerai atau pasan meninggal lalu menikah lagi).

**Comment by ronnyjuny** [comment]
Terima kasih mas Nafies, sangat berguna untuk membuat silsilah ... apakah bisa untuk tampilannya di tambahkan pohon keluarga yang berupa tampilan foto2 nya?
yg ada ini kan berupa tulisan nama2 nya.

**Comment by nafiesl** [comment]
Issue ini saya close, karena duplikat dengan #84
