### ISSUE TITLE
Eror saat backup database

### ISSUE THREAD

**Issue by afifmultimedia** [nafiesl/silsilah#88]
![backupp](https://user-images.githubusercontent.com/9450419/183909457-02f6cf0b-d3fa-4fd2-b36b-ee4055272725.PNG)

Mohon bantuannya mengapa eror saat membuat backup database?

**Comment by azharlihan** [comment]
function proc_open nya tidak tersedia. Mungkin di disable. Bisa coba di enable dulu function nya.
Bisa di informasikan environment php nya? Misal OS, trus instalasi nya pake xampp atau apa gitu..

**Comment by nafiesl** [comment]
Terima kasih sudah dibantu jawab mas @azharlihan. Issue ini saya close. Jika mas @afifmultimedia masih mengalami kendala, silakan re-open issuenya.

Terima kasih.
