### ISSUE TITLE
eror login setelah update profil dan logout

### ISSUE THREAD

**Issue by saifalink** [nafiesl/silsilah#9]
saya coba di demonya mas @nafiesl juga sama kasusnya seperti di webku, hehehe

![eror login lagi](https://user-images.githubusercontent.com/17897618/40652320-2ec80810-6362-11e8-9201-b5be589e7adc.png)
![eror login](https://user-images.githubusercontent.com/17897618/40652321-2ef9d660-6362-11e8-9420-29d26c163fdd.png)

**Comment by nafiesl** [comment]
Oh iya bener mas @saifalink, kita telusuri dulu bugnya ya. Terima kasih banyak untuk submit issuenya mas :smiley:  :+1:

**Comment by nafiesl** [comment]
Sudah diperbaiki mas @saifalink, ternyata sebelumnya keliru ambil nilai untuk password mas, malah emailnnya yang di-hash untuk jadi password :disappointed: 

![shutter_20180529-002](https://user-images.githubusercontent.com/8721551/40656334-ae6ad82c-6376-11e8-923f-9e6ac9338845.jpg)

Terima kasih banyak mas @saifalink untuk kontribusinya. Mantap :+1:

**Comment by ad3n** [comment]
luar biasa

**Comment by nafiesl** [comment]
Mas @ad3n. semangat opensource mas Sur. :smiley: :+1: 

Mas @saifalink, siap mas, terima kasih.
