### ISSUE TITLE
Foto Tidak Tampil Setelah Upload ke CPanel

### ISSUE THREAD

**Issue by diancoxz7** [nafiesl/silsilah#93]
Ijin bertanya pak..saya install di localhost sudah jalan..cuma menu birthday yang masih eror..
Dan ketika saya upload ke CPANEL dengan sub domain.yg upload photo tidak bisa nampil pak...meskipun di folder storage image sudah terupload..tapi yg di folder/public/strorage/image tidak terupload..
ketika say cek di localhost ....saat upload photo masuk ke folder storage/image dan public/storage/image
tapi ketika di upload di website yg online(subdomain) photo hanya masuk ke storage/image dan tidak masuk ke public/storage/image. maka photo tidak menampilkan di profil
kira2 apa yg salah ya pak..trimakasih kiranya bapak mau menjawabnya

**Comment by nafiesl** [comment]
Halo mas @diancoxz7. Terkait foto yang tidak tampil di hosting cpanel, Asumsi saya hal ini disebabkan karena folder `storage/app/public` tidak ter-symlink dengan folder `public/storage`.

Nah ada 2 solusi yang memungkinkan:
1. Jika hostingnya membolehkan `symlink` dan ada fitur console terminal pada cpanel, coba jalankan menjalankan `php artisan storage:link`.
2. Jika dari hosting tidak mengijinkan fitur `symlink`, saran saya: proses upload foto langsung di arahkan ke folder public. Dengan cara menambah konfigurasi storage (lihat video ini untuk tutorialnya: https://www.youtube.com/watch?v=sOfJH20IrvQ)

Silakan dicoba mas. Terima kasih.

**Comment by diancoxz7** [comment]
Terimakasih sekali anda sudah berkenan untuk menjawabnya..
saya baru belajar laravel pak..
sekiranya berkenan untuk bertanya2...
saya sudah coba untuk solusi nomer 2.karena nomer 1 tentu tidak diijinkan dari hosting
saya belum menemukan jawabannya..kiranya jika folder upload photo kita akan rubah tempatnya file apa yang harus dirubah pak.terimkasih

**Comment by diancoxz7** [comment]
Alhamdulillah pak..udah ketemu untuk merubah tempat uploadnya..di filesystem saya rubah sesuai path nya...
Trimakasih pak untuk supportnya..kiranya bapak selalu di berkahi Allah SWT

**Comment by haqi89** [comment]
Settingannya seperti ada mas @diancoxz7

**Comment by nafiesl** [comment]
mas @haqi89 coba baca komentar yang ini: https://github.com/nafiesl/silsilah/issues/93#issuecomment-1425928635
