### ISSUE TITLE
harus login sebelum akses

### ISSUE THREAD

**Issue by diancoxz7** [nafiesl/silsilah#94]
Terimakasih pak nafis untuk berbaginya
saya masih awam dengan laravel..kalau untuk meambahkan agar untuk bisa akses halaman penugunjung harus login dulu logicnya gimana ya pak
terimakasih kiranya mau menjawab

**Comment by nafiesl** [comment]
Ini mas caranya: https://github.com/nafiesl/silsilah/issues/56#issuecomment-647233292

**Comment by diancoxz7** [comment]
trimakasih untuk jawabannya  mas @nafies...kiranya bukan itu yg saya maksud..
yg saya maksud memindahkan halaman pencarian dan menu lainnya bisa diakses setelah pengguna login..saaya sudah bisa memindahkan halaman login ketika akses home.tapi itu hanya direct saja, ke halaman login...maka dari itu menu pencarian masih muncul dan bisa di klik sebelum login...
[url=https://postimg.cc/qNc7L5jQ][img]https://i.postimg.cc/qNc7L5jQ/Screenshot-14.png[/img][/url]

**Comment by nafiesl** [comment]
Maksudnya biar 2 menu itu hanya tampil ketika user sudah login ya, mas @diancoxz7. Caranya gini:

Pada file ini:
https://github.com/nafiesl/silsilah/blob/260ff545047babee99e882777ab29837ef1a0081/resources/views/layouts/partials/nav.blade.php#L21-L24

Diubah jadi seperti ini:

```diff
            <ul class="nav navbar-nav">
+               @auth
                    <li><a href="{{ route('users.search') }}">{{ __('app.search_your_family') }}</a></li>
                    <li><a href="{{ route('birthdays.index') }}">{{ __('birthday.birthday') }}</a></li>
+               @endauth
            </ul>
```

**Comment by diancoxz7** [comment]
Benar pak..trimakasih pak untuk semua ilmunya..kiranya semakin berkah..
BTW jika ada project mungkin kita bisa bekerjasama ya pak..mudah2an..
sekali lagi terimakasih

**Comment by nafiesl** [comment]
Aamiin, sama-sama. Siap mas.
