### ISSUE TITLE
Tidak bisa menampilkan foto di web

### ISSUE THREAD

**Issue by haqi89** [nafiesl/silsilah#97]
Mas kalau ketika upload foto profil tetepi tidak terupdate kira2 kenapa y mas??
Ukuran dah kurang dari 200kb dengan format jpg.
Sama cara buat akun admin gimana ya, soalnya ga nemukan role di database.
Terimakasih

**Comment by nafiesl** [comment]
Sudah terjawab di komentar https://github.com/nafiesl/silsilah/issues/92#issuecomment-1501002241 ya mas. 

Thank you mas @citydenpasar

**Comment by haqi89** [comment]
Mas @nafiesl saya masih belum bisa menampilkan foto di website...
Saya menemukan error saat akan mengeksekusi php artisan storage:link di CPANEL (SHARED HOST)
Untuk direktori file

File >> mysilsilah
Public >> public_html > silsilah.site
Untuk yang di localhost sudah berhasil...

Saya juga sudah melakukan symlink, sesuai petunjuk...
https://haqimkq.blogspot.com/2023/04/cara-membuat-symlink-di-cpanel-hosting.html

tapi masih gagal

https://prnt.sc/v_IWTWTvah0o

**Comment by nafiesl** [comment]
Mas @haqi89 Untuk problem symlink cpanel, mas bisa baca-baca di issue ini: https://github.com/nafiesl/silsilah/issues/93
