### ISSUE TITLE
Menampilkan Urutan Anak ke 1 , Anak ke 2 secara berurutan di Family Chart

### ISSUE THREAD

**Issue by citydenpasar** [nafiesl/silsilah#98]
tolong ubahkan kode agar bisa membuat Bagan secara berurutan di Family Chart

**Comment by haqi89** [comment]
Sepertinya sudah berurutan, asalkan di profil masing2 sudah diisi anak ke......... maka akan tersusun sesuai urutan anak

**Comment by nafiesl** [comment]
Betul seperti yang disampaikan mas @haqi89. Tinggal diisi saja di tiap profil user, urutan anak ke berapa sesuai lahirnya.

**Comment by haqi89** [comment]
Mas @nafiesl saya masih belum bisa menampilkan foto di website... 
Saya menemukan error saat akan mengeksekusi php artisan storage:link di CPANEL (SHARED HOST)
Untuk direktori file

1) File >> mysilsilah
2) Public >> public_html > silsilah.site

Untuk yang di localhost sudah berhasil...

Saya juga sudah melakukan symlink, sesuai petunjuk...
https://haqimkq.blogspot.com/2023/04/cara-membuat-symlink-di-cpanel-hosting.html

tapi masih gagal

**Comment by haqi89** [comment]
https://prnt.sc/v_IWTWTvah0o

**Comment by nafiesl** [comment]
Mas @haqi89, sebaiknya komen terkait problem foto diteruskan di issue yang ini, biar tetap nyambung dengan konteks issuenya:
- https://github.com/nafiesl/silsilah/issues/97

Silakan reopen dan comment di issue itu mas.

**Comment by haqi89** [comment]
Oke siap mas @nafiesl

**Comment by citydenpasar** [comment]
> Sepertinya sudah berurutan, asalkan di profil masing2 sudah diisi anak ke......... maka akan tersusun sesuai urutan anak

bener ada keluarga yang nanya sudah saya jelaskan seperti itu, tapi ternyata diurutkan anaknya berdasarkan Ibunya, karena Kakek Saya mempunyai Istri 2, jadi user menginput urutan anak berdasarkan Ibuknya

**Comment by saifalink** [comment]
> Betul seperti yang disampaikan mas @haqi89. Tinggal diisi saja di tiap profil user, urutan anak ke berapa sesuai lahirnya.

Aku udah sesuaikan tgl lahir anak tp tetep tidak urut,   apa ada yg salah di sistemku?

**Comment by nafiesl** [comment]
Mas @saifalink, yang diisi urutan lahirnya di sini mas.

![Screenshot_20230427-062515_Firefox](https://user-images.githubusercontent.com/8721551/234716124-e71d6512-5cce-450f-b77b-d06bd5004d4e.jpg)

Saat ini tanggal lahir belum dipakai untuk mengurutkan kelahiran anak.

**Comment by saifalink** [comment]
> Mas @saifalink, yang diisi urutan lahirnya di sini mas.
> 
> ![Screenshot_20230427-062515_Firefox](https://user-images.githubusercontent.com/8721551/234716124-e71d6512-5cce-450f-b77b-d06bd5004d4e.jpg)
> 
> Saat ini tanggal lahir belum dipakai untuk mengurutkan kelahiran anak.

![E3EA483D-6D68-4882-A1F8-90BE2AC8CEE0](https://user-images.githubusercontent.com/17897618/234716559-377b8aee-4f1e-4cb3-ba91-dfbc973900ef.png)


Untuk update filenya di sebelah mana ya mas, punyaku data anak ke… blm ada,

**Comment by nafiesl** [comment]
Oo kemungkinan source codenya belum update itu mas @saifalink. Coba mas update softwarenya biar dapat yang terbaru mas.

Catatan:
- kemungkinan perlu update struktur database secara manual untuk kolom tambahan.

**Comment by saifalink** [comment]
> Oo kemungkinan source codenya belum update itu mas @saifalink. Coba mas update softwarenya biar dapat yang terbaru mas.
> 
> Catatan:
> 
> * kemungkinan perlu update struktur database secara manual untuk kolom tambahan.

baik mas, aku coba update softwarenya

**Comment by nafiesl** [comment]
Issue ini kita close ya, karena sudah terjawab.
